spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventory_db}
    username: ${DB_USERNAME:inventory}
    password: ${DB_PASSWORD:inventory}
  jpa:
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    url: /openapi/inventory-service-openapi.yaml
    disable-swagger-default-url: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
